### ISSUE TITLE
Should we add this into Itertools?

### ISSUE THREAD

**Issue by phimuemue** [CAD97/rust-single#1]
I often need this function, and I think it would be a good fit for the [itertools crate](https://crates.io/crates/itertools). What do you think?

**Comment by matklad** [comment]
I'd even game for upstreaming it into stdlib: in practice, people usually call just `next`, and that is bad because it doesn't check for excessive elements. The point of contention would be the error type, of course, but I'd say the stdlib version should return an `Option` with and advise to write a manual match if you need a more precise error handling.

**Comment by CAD97** [comment]
I'm all up for seeing this upstreamed to itertools or stdlib.

But the question of what the return type should be makes this a question I'm not willing to spend the effort bikeshedding.

**Comment by matklad** [comment]
>But the question of what the return type should be makes this a question I'm not willing to spend the effort bikeshedding.

That is 100% understandable :-)

**Comment by CAD97** [comment]
Itertools eventually added [`Itertools::at_most_one`](https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.at_most_one).
